import path from 'node:path';
import type { Configuration, FileMetric } from './model.js';

/** Syntax analysis belongs to TS/JS; other languages get explicit text analysis. */
const extensions: Record<string, string> = {};
for (const [name, suffixes] of [
  ['TypeScript', 'ts tsx mts cts'], ['JavaScript', 'js jsx mjs cjs'],
  ['Python', 'py pyi pyw'], ['Go', 'go'], ['Rust', 'rs'], ['Java', 'java'],
  ['C', 'c h'], ['C++', 'cc cpp cxx hpp hxx hh'], ['C#', 'cs'], ['Kotlin', 'kt kts'],
  ['Swift', 'swift'], ['Dart', 'dart'], ['Ruby', 'rb rake'], ['PHP', 'php phtml'],
  ['Vue', 'vue'], ['Svelte', 'svelte'], ['Scala', 'scala sc'], ['Elixir', 'ex exs'],
  ['Erlang', 'erl hrl'], ['Haskell', 'hs lhs'], ['Lua', 'lua'], ['Perl', 'pl pm'],
  ['R', 'r'], ['Julia', 'jl'], ['Objective-C', 'm mm'], ['Fortran', 'f f90 f95'],
  ['Shell', 'sh bash zsh'], ['PowerShell', 'ps1 psm1'], ['SQL', 'sql'],
  ['HTML', 'html htm'], ['CSS', 'css scss sass less'], ['Protocol Buffers', 'proto'],
  ['Terraform', 'tf hcl'], ['Zig', 'zig'], ['OCaml', 'ml mli'], ['Clojure', 'clj cljs cljc'],
  ['F#', 'fs fsx'], ['Bazel', 'bzl'], ['Solidity', 'sol'], ['Assembly', 's asm']
]) for (const suffix of suffixes!.split(' ')) extensions[`.${suffix}`] = name!;

export function sourceLanguage(file: string, config: Pick<Configuration, 'sourceExtensions'>): { name: string; mode: 'syntax' | 'text' } | null {
  const extension = path.extname(file).toLowerCase();
  const name = extensions[extension] ?? (config.sourceExtensions.includes(extension) ? `Extension ${extension}` :
    ['BUILD', 'BUILD.bazel', 'WORKSPACE', 'WORKSPACE.bazel'].includes(path.basename(file)) ? 'Bazel' : null);
  return name ? { name, mode: name === 'TypeScript' || name === 'JavaScript' ? 'syntax' : 'text' } : null;
}

export function isGeneratedSource(source: string): boolean {
  return source.slice(0, 1_024).split(/\r?\n/).some(line =>
    /^\s*(?:\/\/|\/\*|\*|#|--|<!--|;|%).*(?:@generated\b|auto[- ]generated\b|automatically generated\b|code generated.*do not edit|generated by.*do not edit)/i.test(line));
}

export function textMetric(file: string, source: string): FileMetric {
  const lines = source.length === 0 ? 0 : source.split(/\r\n|[\r\n\u2028\u2029]/).length - Number(/[\r\n\u2028\u2029]$/.test(source));
  return { file, lines, functions: [] };
}
